version: "3.9"

services:
  backend-app:
    image: iac-app-demo/backend-app
    build:
      context: .
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped